### ISSUE TITLE
how to upload a simple single page website?

### ISSUE THREAD

**Issue by jpritikin** [ethersphere/swarm-extension#106]
I have a single page website composed of an index.html plus images and javascript. Is there any easy way to fix all the path references from (E.g. `./favicons/apple-touch-icon.png`) to the appropriate bzz urls? What is the recommended way to do this?

**Comment by nugaon** [comment]
because all referenced files you have (presumably) uploaded in one folder with Bee, you can refer to the resources by relative links as you would do that normally, because the files share one common manifest. Thereby, you don't need to address them with BZZ URLs.

On the other hand, if you want to refer to an external Swarm resource, you have to acquire its BZZ URL in order to work in web2 and web3. For that, you only need to create the corresponding CID of the Swarm hash reference of the resource. The swarm-extension provides an injected library to do that (through the `swarm.bzzLink.hashToCid(swarmReference).toString()`)

**Comment by nugaon** [comment]
also, if you use swarm CIDs, don't forget to use it in [Swarm HTML elements](https://github.com/ethersphere/swarm-extension#swarm-html)

**Comment by jpritikin** [comment]
> because all referenced files you have (presumably) uploaded in one folder with Bee

Yes, I used the swarm extension to upload the whole folder.

> you can refer to the resources by relative links as you would do that normally, because the files share one common manifest. 

Okay, great, so why doesn't 22324a8f2cedaca8448543ccc1e40e634a34fc98e74a3986d5465388f5e75c74 work like https://ipfs.io/ipfs/QmY9WUjD3YYfyzmegDYxE8yZFcNT3L9TRQSGCJQaWjXxwk/ ?

**Comment by nugaon** [comment]
can you link the page on Swarm so that I can check out what is the problem or could you elaborate your issue please?

**Comment by jpritikin** [comment]
22324a8f2cedaca8448543ccc1e40e634a34fc98e74a3986d5465388f5e75c74 is a swarm hash. Browse to bzz://22324a8f2cedaca8448543ccc1e40e634a34fc98e74a3986d5465388f5e75c74

**Comment by nugaon** [comment]
as I checked [your page](https://bah5qcgzaeizevdzm5wwkqrefipgmdzaomnfdj7ey45fdtbwvizjyr5phlr2a.bzz.link/) the folder that you uploaded for the webpage does not have the `static/js` and the `favicons` folders uploaded. 
it does seem a swarm-extension related issue as it also does not work without the extension

**Comment by jpritikin** [comment]
> as I checked [your page](https://bah5qcgzaeizevdzm5wwkqrefipgmdzaomnfdj7ey45fdtbwvizjyr5phlr2a.bzz.link/) the folder that you uploaded for the webpage does not have the static/js and the favicons folders uploaded.

Why not? The source folder that I tried to upload with the swarm extension has these files:

```
./favicon.ico
./favicons
./favicons/android-chrome-192x192.png
./favicons/android-chrome-512x512.png
./favicons/apple-touch-icon.png
./favicons/browserconfig.xml
./favicons/favicon-16x16.png
./favicons/favicon-32x32.png
./favicons/favicon.ico
./favicons/mstile-150x150.png
./favicons/safari-pinned-tab.svg
./favicons/site.webmanifest
./robots.txt
./static
./static/media
./static/media/transfer-success.42bf35a1.svg
./static/media/wallet.7e471e4c.svg
./static/media/arrow-up.5a74c4fc.svg
./static/media/dollar.dc4d8d78.svg
./static/media/hand.3d975026.svg
./static/media/usdp.6c3f3672.png
./static/media/error-icon.c3ad6ff0.svg
./static/media/logo.8c970dde.svg
./static/css
./static/css/main.5d7e79b3.chunk.css
./static/css/main.5d7e79b3.chunk.css.map
./static/js
./static/js/main.13adbc81.chunk.js
./static/js/runtime-main.c39837bc.js
./static/js/2.f3ce03a3.chunk.js
./static/js/3.b14382bb.chunk.js
./static/js/2.f3ce03a3.chunk.js.LICENSE.txt
./static/js/main.13adbc81.chunk.js.map
./static/js/runtime-main.c39837bc.js.map
./static/js/2.f3ce03a3.chunk.js.map
./static/js/3.b14382bb.chunk.js.map
./index.html
./asset-manifest.json
```

>  it does seem a swarm-extension related issue as it also does not work without the extension

What do you mean? Why did you close this issue?

**Comment by jpritikin** [comment]
Should I use the [Swarm CLI](https://github.com/ethersphere/swarm-cli) to upload the folder if the google extension is broken?

**Comment by agazso** [comment]
> Should I use the [Swarm CLI](https://github.com/ethersphere/swarm-cli) to upload the folder if the google extension is broken?

I suggest you to try it, with it you can also list the content of you manifests with the following command. You can see then that what you uploaded is different than your source directory that you provided above.
```
swarm-cli manifest list 22324a8f2cedaca8448543ccc1e40e634a34fc98e74a3986d5465388f5e75c74 
44421825191cb75498975f7638e39d9c3badfd0287d1972950643e5e7a2ef0e3 /.swarmgatewaymeta.json
d81c88c47cbf888bc63bb6089614a24f57f3e936a4d1398fd81627eb7a24e0a4 /android-chrome-192x192.png
958888d6fb0212606b422ce0204d368ecff05260db7baa1aed46ea5007bfc45f /android-chrome-512x512.png
ab4cdb61fce8d0c0affb75a0cd1118af855623e8ede820c3a91ffeeca716f62c /apple-touch-icon.png
2ec733399e36a030c180b67ee6ab661f180015aceba0952f6f97001eeb4fdcc6 /asset-manifest.json
2f2f00abab72403aa4b65ff623c360fd8b6292c398b3cde74b85c5188c239b84 /browserconfig.xml
1e7e26c75ad6cf14ebbb8d4bdf574954c52314c7f1336adc737d4dc55ccb6096 /css/main.5d7e79b3.chunk.css
968f195d44c4c5a4f93a38dc73de340545cbd7e4687540f4c9582a5ed6cb0fa7 /css/main.5d7e79b3.chunk.css.map
3282585396712020e140043f8f369ae3b4f2633a0d0c8632fd30749bfe9269f1 /favicon-16x16.png
8ae8ed737f1107c99870743a094d2395e4f6ca7563163349fb66d0cbfd239806 /favicon-32x32.png
ee4863d3eee9119633af8d970ed1175530db1b87ee8385935a5ffb32725af4a6 /favicon.ico
d57ea549ade1d4c71851b9699bc171b9e607e9d81705e3150a63db539b802e15 /index.html
36f54ed023fe8af2b10f5444e978e2e259c2bbd6e7a6e2fd61b39bc3db30c900 /js/2.f3ce03a3.chunk.js
d7c510c70d8b73a35828b4af8da7a3c80804e5965dc4f235ab43e6b70a914e95 /js/2.f3ce03a3.chunk.js.LICENSE.txt
0de00b995e5f1b9dacd5ed5f2bb76a6bbe1769c878ebd7485301b83542891f39 /js/2.f3ce03a3.chunk.js.map
313e2f591b86985da02996b697d13c744c3ba04b5a3964db73b1012a70374063 /js/3.b14382bb.chunk.js
e633c31b2b3c15e6fa1a32dcb38e3f0d8ecb03005c685981aeea13e567b454e8 /js/3.b14382bb.chunk.js.map
5dbcbb9a17e480fb8bba6a1ef4389db11a4996adba90f1eb0cacbb60dde1d6a0 /js/main.13adbc81.chunk.js
234b600beb1b786fc6a56dd78f432e9981abf6722a619b787daf44959d85f9cd /js/main.13adbc81.chunk.js.map
d37c0365944007a4e8f673b4bab32f53fa4ad2486f859fac67d9ccf0ab27bf7e /js/runtime-main.c39837bc.js
81f89abc816a2cd29687c9c1b82e1bd3cad4c0cbf8b41f7d553909220ea5ec12 /js/runtime-main.c39837bc.js.map
f2309372083424187ca99e8aa1d9133c76d72e232c3008afe8e96502f5a8ea8f /media/arrow-up.5a74c4fc.svg
a05080233ea994fd3c806172b3521b05c2a774ee496000434296a4c652a805ac /media/dollar.dc4d8d78.svg
5fd1966293087d214a690a2379a50585bb2da196294906818a398967d77e4fab /media/error-icon.c3ad6ff0.svg
42b67f97ba939007d44047014feb717392410d7482cdcd0e90b8439c5732e24c /media/hand.3d975026.svg
1be34315e23ab8f0536a916c6189bac32d3a219621eaf1ecdbbf8f6629a33754 /media/logo.8c970dde.svg
11e5c334faf1b253b4e28e38770d49cfde7d80a4629cebbb0036137adbdc0f11 /media/transfer-success.42bf35a1.svg
bcbae5a87d82736b8685fad9b89b3fe53fed034c89aa264d40ca335a29564ee2 /media/usdp.6c3f3672.png
724d8bfa750c6e3c2c8ad8502e4193050ec9346e89d11acfcce7f946666725f8 /media/wallet.7e471e4c.svg
7e76701d2e411ea6329ae9a32ab130248b6bb512703b35d084dc793e85a73874 /mstile-150x150.png
3d9b11d5b45d1af5a5a294e637c3629f89124fe049e1b10e4ec834c719ce0b99 /robots.txt
fdecf2c37f142d7e6cacf5f64e4bce3b447c1a9baf885149590775e58defdad3 /safari-pinned-tab.svg
451c38f37c8ce9106d68fcfdb1b52b51daa737caff1f26c2ad1c40c67669a6ef /site.webmanifest
```

**Comment by jpritikin** [comment]
[Unfortunately swarm-cli seems broken with node 18.](https://github.com/ethersphere/swarm-cli/issues/370) I guess I'll come back to this later.

**Comment by nugaon** [comment]
> What do you mean? Why did you close this issue?

my bad, I had a typeo, let me correct:

> it does  *not* seem a swarm-extension related issue as it also does not work without the extension

thereby the swarm-extension is *not* broken.

I checked your manifest under that hash that you pasted here and I was right;
your uploaded directory items are the following:
```
swarm-cli manifest list 22324a8f2cedaca8448543ccc1e40e634a34fc98e74a3986d5465388f5e75c74

44421825191cb75498975f7638e39d9c3badfd0287d1972950643e5e7a2ef0e3 /.swarmgatewaymeta.json
d81c88c47cbf888bc63bb6089614a24f57f3e936a4d1398fd81627eb7a24e0a4 /android-chrome-192x192.png
958888d6fb0212606b422ce0204d368ecff05260db7baa1aed46ea5007bfc45f /android-chrome-512x512.png
ab4cdb61fce8d0c0affb75a0cd1118af855623e8ede820c3a91ffeeca716f62c /apple-touch-icon.png
2ec733399e36a030c180b67ee6ab661f180015aceba0952f6f97001eeb4fdcc6 /asset-manifest.json
2f2f00abab72403aa4b65ff623c360fd8b6292c398b3cde74b85c5188c239b84 /browserconfig.xml
1e7e26c75ad6cf14ebbb8d4bdf574954c52314c7f1336adc737d4dc55ccb6096 /css/main.5d7e79b3.chunk.css
968f195d44c4c5a4f93a38dc73de340545cbd7e4687540f4c9582a5ed6cb0fa7 /css/main.5d7e79b3.chunk.css.map
3282585396712020e140043f8f369ae3b4f2633a0d0c8632fd30749bfe9269f1 /favicon-16x16.png
8ae8ed737f1107c99870743a094d2395e4f6ca7563163349fb66d0cbfd239806 /favicon-32x32.png
ee4863d3eee9119633af8d970ed1175530db1b87ee8385935a5ffb32725af4a6 /favicon.ico
d57ea549ade1d4c71851b9699bc171b9e607e9d81705e3150a63db539b802e15 /index.html
36f54ed023fe8af2b10f5444e978e2e259c2bbd6e7a6e2fd61b39bc3db30c900 /js/2.f3ce03a3.chunk.js
d7c510c70d8b73a35828b4af8da7a3c80804e5965dc4f235ab43e6b70a914e95 /js/2.f3ce03a3.chunk.js.LICENSE.txt
0de00b995e5f1b9dacd5ed5f2bb76a6bbe1769c878ebd7485301b83542891f39 /js/2.f3ce03a3.chunk.js.map
313e2f591b86985da02996b697d13c744c3ba04b5a3964db73b1012a70374063 /js/3.b14382bb.chunk.js
e633c31b2b3c15e6fa1a32dcb38e3f0d8ecb03005c685981aeea13e567b454e8 /js/3.b14382bb.chunk.js.map
5dbcbb9a17e480fb8bba6a1ef4389db11a4996adba90f1eb0cacbb60dde1d6a0 /js/main.13adbc81.chunk.js
234b600beb1b786fc6a56dd78f432e9981abf6722a619b787daf44959d85f9cd /js/main.13adbc81.chunk.js.map
d37c0365944007a4e8f673b4bab32f53fa4ad2486f859fac67d9ccf0ab27bf7e /js/runtime-main.c39837bc.js
81f89abc816a2cd29687c9c1b82e1bd3cad4c0cbf8b41f7d553909220ea5ec12 /js/runtime-main.c39837bc.js.map
f2309372083424187ca99e8aa1d9133c76d72e232c3008afe8e96502f5a8ea8f /media/arrow-up.5a74c4fc.svg
a05080233ea994fd3c806172b3521b05c2a774ee496000434296a4c652a805ac /media/dollar.dc4d8d78.svg
5fd1966293087d214a690a2379a50585bb2da196294906818a398967d77e4fab /media/error-icon.c3ad6ff0.svg
42b67f97ba939007d44047014feb717392410d7482cdcd0e90b8439c5732e24c /media/hand.3d975026.svg
1be34315e23ab8f0536a916c6189bac32d3a219621eaf1ecdbbf8f6629a33754 /media/logo.8c970dde.svg
11e5c334faf1b253b4e28e38770d49cfde7d80a4629cebbb0036137adbdc0f11 /media/transfer-success.42bf35a1.svg
bcbae5a87d82736b8685fad9b89b3fe53fed034c89aa264d40ca335a29564ee2 /media/usdp.6c3f3672.png
724d8bfa750c6e3c2c8ad8502e4193050ec9346e89d11acfcce7f946666725f8 /media/wallet.7e471e4c.svg
7e76701d2e411ea6329ae9a32ab130248b6bb512703b35d084dc793e85a73874 /mstile-150x150.png
3d9b11d5b45d1af5a5a294e637c3629f89124fe049e1b10e4ec834c719ce0b99 /robots.txt
fdecf2c37f142d7e6cacf5f64e4bce3b447c1a9baf885149590775e58defdad3 /safari-pinned-tab.svg
451c38f37c8ce9106d68fcfdb1b52b51daa737caff1f26c2ad1c40c67669a6ef /site.webmanifest
```

so the problem is in your one-pager application.

**Comment by jpritikin** [comment]
Where did the `static` subdirectory go? I see `/js/2.f3ce03a3.chunk.js` but that file should be located under `static/js/2.f3ce03a3.chunk.js`. It looks like the swarm extension omitted the `static` subdirectory.

**Comment by jpritikin** [comment]
Here is a [screencast](https://www.youtube.com/watch?v=aH5I2Q9K9S8). Is there a difference between the `Add Folder` and `Add Website` buttons?

**Comment by jpritikin** [comment]
Please explain how this is not a swarm extension bug.

**Comment by vojtechsimetka** [comment]
Hi @jpritikinthank you very much for following up here. The difference between `Add Folder` and `Add Website` is that the Add Website actually checks if there is `index.html` in the uploaded folder. In another product we actually removed this distinction https://gateway.ethswarm.org

So the swarm extension is actually embedding as separate product called bee-dashboard. The bug is there and I will investigate. Thank you for reporting it, lets move the discussion there please :) https://github.com/ethersphere/bee-dashboard/issues/363

**Comment by jpritikin** [comment]
Can you do a new release including https://github.com/ethersphere/bee-dashboard/pull/365 ? Thanks!

**Comment by jpritikin** [comment]
I tried again with v0.3.1. I got bzz hash `b5dae35498c8b42a56156f94b5f2b9d0daf4184faf87c3113c941890f1f4d246`. The files seem to be placed in the correct location in the directory nesting. However, the site still doesn't work. Any idea why?

**Comment by jpritikin** [comment]
It should look like 
![image](https://user-images.githubusercontent.com/2002771/173207170-9789d4a0-ee28-458d-8319-64244926fb87.png)
