### ISSUE TITLE
how to upload a simple single page website

### ISSUE THREAD

**Issue by jpritikin** [ethersphere/swarm-extension#120]
I just want to reopen #106 since the issue in bee dashboard was fixed. Website upload still doesn't work and it is not clear why not.

**Comment by vojtechsimetka** [comment]
Hi, yes I think the extension is just waiting to be approved by google and released on google store. But lets keep this issue here for now.

**Comment by jpritikin** [comment]
I'm pretty sure I used the latest release. I was careful to check the version,
![image](https://user-images.githubusercontent.com/2002771/174147713-95af10b6-89a1-44ec-badd-b7ccc0ecdfa8.png)

**Comment by vojtechsimetka** [comment]
So I just tried on `master` branch in `bee-dashboard`. It works, we probably had some version conflict because this PR fixes it. We will release new swarm-extension soon. Thanks for being so persistent! :)

**Comment by jpritikin** [comment]
> this PR fixes it

Which PR?

**Comment by jpritikin** [comment]
swarm-extension 0.4? Still waiting for the [chrome store](https://chrome.google.com/webstore/detail/ethereum-swarm-extension/afpgelfcknfbbfnipnomfdbbnbbemnia) to update.

**Comment by jpritikin** [comment]
I tried with swarm-extension 0.5. The upload attempt results in swarm hash 22324a8f2cedaca8448543ccc1e40e634a34fc98e74a3986d5465388f5e75c74. So it looks like bug #106 got unfixed?

**Comment by nugaon** [comment]
yes, the new version contains other changes.

we put onto the today's agenda to plan making [bee-dashboard](https://github.com/ethersphere/bee-dashboard) compatible again with Swarm Extension.

I will tag you to the release PR which will solve this issue.

**Comment by jpritikin** [comment]
I tried with swarm-extension 0.6. The upload results in swarm hash `f16c29a9985bd1006a66f22c9571b9361a101fb4dc8a259c199b44d3511315b0`. The site still doesn't load, but I can't load `bzz://swarm.eth/` or `bzz://bzzwiki.eth` either so maybe something else is wrong?

**Comment by nugaon** [comment]
> I tried with swarm-extension 0.6. The upload results in swarm hash `f16c29a9985bd1006a66f22c9571b9361a101fb4dc8a259c199b44d3511315b0`.

I could properly load https://bah5qcgza6fwctkmylpiqa2tg6iwjk4nzgynbah5u3sfclhaztncnguitcwya.bzz.link/ (which is the corresponding CID for hash `f16c29a9985bd1006a66f22c9571b9361a101fb4dc8a259c199b44d3511315b0`), I don't see any errors in the console.

![Screenshot from 2022-10-06 13-44-49](https://user-images.githubusercontent.com/50576770/194304428-1fd839df-25a3-4297-856a-534bf966c2c2.png)

> The site still doesn't load, but I can't load `bzz://swarm.eth/` or `bzz://bzzwiki.eth` either so maybe something else is wrong?
> 
> I'm using a bee node on my local network instead of `localhost`. Is that a problem?

it is not a problem, but the dashboard cannot change the ENS resolver RPC address of your Bee node. you have to configure it in the Bee's configuration.

**Comment by jpritikin** [comment]
I agree that the site seems to load correctly with the bzz.link url.

> the dashboard cannot change the ENS resolver RPC address of your Bee node.

Oh, my ENS resolver is broken? I put in a fresh API endpoint and it seemed to worked in the logs,

````
Oct 06 12:22:12 glow bee[26930]: "time"="2022-10-06 12:22:12.527975" "level"="info" "logger"="node/multiresolver" "msg"="connected" "tld"="" "endpoint"="https://mainnet.infura.io/v3/b118a5b048a94416b6750140f19ad421"
````

Is there a way to test this? I still can't load bzz://swarm.eth using the chrome extension.

**Comment by jpritikin** [comment]
Should I file a new bug? How to move forward here?
