### ISSUE TITLE
can't load pages from swarm

### ISSUE THREAD

**Issue by jpritikin** [ethersphere/swarm-extension#146]
Uploading a website #120 is working, however I can't load and render bzz links using the chrome extension version 0.6.0. I tried bzz://swarm.eth/, bzz://pastebee.eth/, and bzz://bzzwiki.eth. How to troubleshoot?

**Comment by agazso** [comment]
You can try if Bee works correctly by checking these addresses at the HTTP endpoints. For example: `http://localhost:1633/bzz/bzzwiki.eth`

Please note that some websites (for example the `bzzwiki.eth`) may break when addressed like this, because they may rely being located on the root path. Alternatively you can try the subdomain addressing schema: `http://bzzwiki.eth.swarm.localhost:1633`
However this only works in Chrome and Firefox.

**Comment by jpritikin** [comment]
> because they may rely being located on the root path

Ah, I think that is what is going wrong:
````
Loading failed for the <script> with source “https://mtm.swarm.foundation/matomo.js”. [swarm.eth:1:1](http://glow.lan:1633/bzz/swarm.eth/)
Loading failed for the <script> with source “http://glow.lan:1633/_next/static/chunks/webpack-ee7e63bc15b31913.js”. [swarm.eth:32:1](http://glow.lan:1633/bzz/swarm.eth/)
Loading failed for the <script> with source “http://glow.lan:1633/_next/static/chunks/main-2616d0a9f4d67031.js”. [swarm.eth:32:1](http://glow.lan:1633/bzz/swarm.eth/)
Loading failed for the <script> with source “http://glow.lan:1633/_next/static/chunks/pages/_app-d1d66b1f74b2e7d9.js”. [swarm.eth:32:1](http://glow.lan:1633/bzz/swarm.eth/)
Loading failed for the <script> with source “http://glow.lan:1633/_next/static/chunks/73-4e585fca58eb68b4.js”. [swarm.eth:32:1](http://glow.lan:1633/bzz/swarm.eth/)
Loading failed for the <script> with source “http://glow.lan:1633/_next/static/chunks/882-cd5ff1f0f14ce8a1.js”. [swarm.eth:32:1](http://glow.lan:1633/bzz/swarm.eth/)
Loading failed for the <script> with source “http://glow.lan:1633/_next/static/chunks/framework-7751730b10fa0f74.js”. [swarm.eth:32:1](http://glow.lan:1633/bzz/swarm.eth/)
Loading failed for the <script> with source “http://glow.lan:1633/_next/static/msD-Sl8CdseY-jUF96zTP/_buildManifest.js”. [swarm.eth:32:1](http://glow.lan:1633/bzz/swarm.eth/)
````

 It seems like the swarm extension doesn't address this yet?

**Comment by agazso** [comment]
There is a new version in the making that has support for this but that has not been released yet.

Here is a link to the original issue: https://github.com/ethersphere/swarm-extension/issues/96

**Comment by jpritikin** [comment]
I guess this is a duplicate.
